baseURL = "https://herculan0.github.io"
languageCode = "pt-br"
theme = "aafu"

[deployment]
  [[deployment.targets]]
    name = "S3"
    URL = "s3://herculano.xyz?region=us-east-1"
    cloudFrontDistributionID = ""
  [[deployment.matchers]]
    #  Cache static assets for 1 year.
    pattern = "^.+\\.(js|css|svg|ttf|png|jpg|svg|woff|woff2)$"
    cacheControl = "max-age=31536000, no-transform, public"

[params]
    title = "42"
    author = "Lucas Herculano"
    description = "A vida, o Universo e tudo mais, avoam como o vento"
    copyright = "Herculano's 2020"

    [params.theme]
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "light"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = false
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Lucas Herculano"
		tagline = "SRE/DevOps"
		location = "Belo Horizonte, BR"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "https://linkedin.com/in/lucasgherculano"
            title = "LinkedIn"		
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "https://github.com/herculan0"
            title = "GitHub"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"
    [[params.showInAccordion]]
        item = "education"

    [params.aboutme]
        title = "sobre mim"
        icon = "fas fa-user"
          description = "**Obs: estou mais barbudo e cabeludo do que na foto, brevemente irei atualizar**, Formado em Análise e Desenvolvimento de Sistemas pelo Pitágoras, trabalho atualmente focado em trazer confiança à produtos de software como Site Reliability Engineer. Alguns dos meus hobbies: programar, ler, cozinhar e plantar. Sou vegano pelos animais, tenho uma cachorra chamada Xena e uma companheira incrível chamada Tainá."

    # Experience section
    [params.experience]
        title = "experiências profissionais"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Estagiário de Infraestrutura"
            dates = "2018 - *2020*"
            link = "https://br.linkedin.com/company/prodemge"
            company = "Prodemg"
            details = "Linux, Virtualização, Servidores Web. Grupos de Trabalho de DevOps e Blockchain"
        [[params.experience.list]]
            position = "Analista de Suporte"
            dates = "2020 - 2020"
            link = "#"
            company = "Company Name"

    # Education section
    [params.education]
        title = "Formação"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "Análise e Desenvolvimento de Sistemas"
            college = "Faculdade Pitágoras"
            dates = "2018 - 2020"
            thesis_title = "Sistema of humans on other humans: a study of human behavior."
            thesis_link = "#"
        [[params.education.list]]
            degree = "M.S. in Subject"
            college = "University of State-City"
            dates = "2013 - 2018"
            thesis_title = "Effect of humans on other humans: a study of human behavior."
            thesis_link = "#"
        [[params.education.list]]
            degree = "B.S. in Subject"
            college = "University of State-City"
            dates = "2004 - 2009"

    # Publication section
    [params.publication]
        title = "Publications"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Journal Articles", "Proceedings"]

        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            link = "#"
            type = "Journal Articles"

        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            link = "#"
            type = "Journal Articles"
		
        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            link = "#"
            type = "Proceedings"

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"            

    # Skill section
    [params.skill]
        title = "habilidades"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Linux Administration"
            skillrating = 55
        [[params.skill.list]]
            skill = "Python" 
            skillrating = 35
        [[params.skill.list]]
            skill = "Cloud Computing"
            skillrating = 40
        [[params.skill.list]]
            skill = "Containers"
            skillrating = 45


    # Hobby section
    [params.hobby]
        title = "hobbies"
        icon = "fas fa-gamepad"
        [[params.hobby.list]]		
		    hobby = "ler"
        [[params.hobby.list]]		
		    hobby = "cozinhar"
        [[params.hobby.list]]		
		    hobby = "programar"
        [[params.hobby.list]]		
		    hobby = "viajar"
